"""Remove name column from credentials

Revision ID: a9172c5ca8a0
Revises: 9509237fa4b3
Create Date: 2025-04-07 21:28:54.070412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9172c5ca8a0'
down_revision = '9509237fa4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_credentials_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index('ix_credentials_name', ['name'], unique=1)

    # ### end Alembic commands ###
